spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:postgresql://10.52.83.203:5432/personasdb
spring.datasource.username=appuser
spring.datasource.password=${DB_PASSWORD:12345}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.batch_size=1000